<?php

namespace ContatosBundle\Repository;

use ContatosBundle\Entity\Contatos;
use Doctrine\ORM\EntityRepository;


/**
 * ContatosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContatosRepository extends EntityRepository
{
}
