<?php

namespace AgendaBundle\Repository;

use AgendaBundle\Entity\Servicos;
use Doctrine\ORM\EntityRepository;

/**
 * AgendadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicosRepository extends EntityRepository
{

}